services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dotlancheProducao
      MONGO_INITDB_ROOT_PASSWORD: P455w0rd
    ports:
    - "27017:27017" 

  mock:
    hostname: mock-produto
    image: jkris/mountebank:latest
    volumes:
    - ./mockFiles:/imposters
    ports:
    - 2525:2525
    - 8002:8002
    command: --configfile /imposters/imposters.ejs --allowInjection

  api:
    build: 
      context: .
      dockerfile: ./src/Drivers/Dotlanche.Producao.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=mongodb://dotlancheProducao:P455w0rd@db:27017/?appName=dotlanche-producao
      - Integrations__ProdutoService__BaseAddress=http://mock-produto:8002

