apiVersion: v1
kind: Service
metadata:
  name: dotlanche-producao-svc
spec:
  type: NodePort
  selector:
    app: dotlanche-producao
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
